# Generated by Django 4.1.1 on 2022-11-07 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='name',
            field=models.CharField(max_length=150, null=True, verbose_name='Video Name'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='video_set',
            field=models.ForeignKey(help_text='Video Set of the uploading videos', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='videos.videoset'),
        ),
    ]
