# Generated by Django 3.2.16 on 2022-11-13 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0004_remove_inferencedimage_detection_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inferencedvideo',
            name='detection_info',
        ),
    ]
